// Generated by `wit-bindgen` 0.10.0. DO NOT EDIT!
#include "testfs.h"


__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

__attribute__((__export_name__("openfile")))
void __wasm_export_testfs_openfile(void) {
  testfs_openfile();
}

extern void __component_type_object_force_link_testfs(void);
void __component_type_object_force_link_testfs_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_testfs();
}
