// Generated by `wit-bindgen` 0.10.0. DO NOT EDIT!
#ifndef __BINDINGS_TESTFS_H
#define __BINDINGS_TESTFS_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `testfs`
void testfs_openfile(void);

#ifdef __cplusplus
}
#endif
#endif
